<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>52a0a925-4296-4ad0-a62a-75ff861c491f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\Img\Anh-nen-trang-mo-ao.jpg" />
    <None Include="wwwroot\Img\avatar-shin-cute-8.jpg" />
    <None Include="wwwroot\Img\Img_banner.png" />
    <None Include="wwwroot\Img\logoReal.png" />
    <None Include="wwwroot\Img\pngtree-avatar-chinese-cute-cici-profile-png-image_8626546.png" />
    <None Include="wwwroot\Img\pngtree-padel-tennis-player-man-isolated-white-background-cut-out-player-padel-photo-image_33805294.jpg" />
    <None Include="wwwroot\Img\qrr.jpg" />
    <None Include="wwwroot\Img\SanMau1.jpg" />
    <None Include="wwwroot\Img\SanMau2.jpg" />
    <None Include="wwwroot\Img\SanMau3.jpg" />
    <None Include="wwwroot\Img\SanMau4.jpg" />
    <None Include="wwwroot\Img\SanMau5.jpg" />
    <None Include="wwwroot\Img\SanMau6.jpg" />
    <None Include="wwwroot\Img\SanMau7.jpg" />
    <None Include="wwwroot\Img\SanMau8.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0" />
    <PackageReference Include="Mscc.GenerativeAI" Version="3.1.0" />
  </ItemGroup>

</Project>
