// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pickleball_Smash.Data;

#nullable disable

namespace Pickleball_Smash.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503090433_AddYeuCauHuy")]
    partial class AddYeuCauHuy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pickleball_Smash.Models.BangGiaKhungGio", b =>
                {
                    b.Property<int>("MaGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGia"));

                    b.Property<decimal?>("GiaTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KhungGio")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<int?>("SanID")
                        .HasColumnType("int");

                    b.HasKey("MaGia");

                    b.HasIndex("SanID");

                    b.ToTable("BANG_GIA_KHUNG_GIO", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DanhGia", b =>
                {
                    b.Property<int>("DanhGiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhGiaID"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DonDatSanID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<int?>("SanID")
                        .HasColumnType("int");

                    b.Property<int?>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("DanhGiaID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("SanID");

                    b.ToTable("DANH_GIA", null, t =>
                        {
                            t.HasCheckConstraint("CK_DANH_GIA_SoSao", "SoSao >= 1 AND SoSao <= 5");
                        });
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DonDatSan", b =>
                {
                    b.Property<int>("DonDatSanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonDatSanID"));

                    b.Property<string>("KhungGio")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<DateOnly?>("NgayChoi")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<int?>("SanID")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTienGiam")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDon")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int?>("VoucherID")
                        .HasColumnType("int");

                    b.Property<bool>("YeuCauHuy")
                        .HasColumnType("bit");

                    b.HasKey("DonDatSanID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("SanID");

                    b.HasIndex("VoucherID");

                    b.ToTable("DON_DAT_SAN", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.HinhAnhSan", b =>
                {
                    b.Property<int>("HinhAnhID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HinhAnhID"));

                    b.Property<string>("DuongDanURL")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int?>("SanID")
                        .HasColumnType("int");

                    b.HasKey("HinhAnhID");

                    b.HasIndex("SanID");

                    b.ToTable("HINH_ANH_SAN", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.LichSuChat", b =>
                {
                    b.Property<int>("ChatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatID"));

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanHoiAI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ChatID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("LICH_SU_CHAT", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungID"));

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("HoTen")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SDT")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("VaiTro")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("NguoiDungID");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NGUOI_DUNG", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.SanPickleball", b =>
                {
                    b.Property<int>("SanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SanID"));

                    b.Property<decimal?>("GiaCoBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiSan")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("TenSan")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("SanID");

                    b.ToTable("SAN_PICKLEBALL", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanID"));

                    b.Property<int?>("DonDatSanID")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PhuongThuc")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<decimal?>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("ThanhToanID");

                    b.HasIndex("DonDatSanID");

                    b.ToTable("THANH_TOAN", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherID"));

                    b.Property<decimal?>("GiaTriDonToiThieu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaTriGiam")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiamToiDa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiGiamGia")
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("MaVoucher")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("MoTa")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("SoLuongDaDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("VoucherID");

                    b.HasIndex("MaVoucher")
                        .IsUnique();

                    b.ToTable("VOUCHER", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.BangGiaKhungGio", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.SanPickleball", "SanPickleball")
                        .WithMany("BangGiaKhungGios")
                        .HasForeignKey("SanID");

                    b.Navigation("SanPickleball");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DanhGia", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("NguoiDungID");

                    b.HasOne("Pickleball_Smash.Models.SanPickleball", "SanPickleball")
                        .WithMany("DanhGias")
                        .HasForeignKey("SanID");

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPickleball");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DonDatSan", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonDatSans")
                        .HasForeignKey("NguoiDungID");

                    b.HasOne("Pickleball_Smash.Models.SanPickleball", "SanPickleball")
                        .WithMany("DonDatSans")
                        .HasForeignKey("SanID");

                    b.HasOne("Pickleball_Smash.Models.Voucher", "Voucher")
                        .WithMany("DonDatSans")
                        .HasForeignKey("VoucherID");

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPickleball");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.HinhAnhSan", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.SanPickleball", "SanPickleball")
                        .WithMany("HinhAnhSans")
                        .HasForeignKey("SanID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SanPickleball");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.LichSuChat", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.NguoiDung", "NguoiDung")
                        .WithMany("LichSuChats")
                        .HasForeignKey("NguoiDungID");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.ThanhToan", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.DonDatSan", "DonDatSan")
                        .WithMany("ThanhToans")
                        .HasForeignKey("DonDatSanID");

                    b.Navigation("DonDatSan");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DonDatSan", b =>
                {
                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonDatSans");

                    b.Navigation("LichSuChats");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.SanPickleball", b =>
                {
                    b.Navigation("BangGiaKhungGios");

                    b.Navigation("DanhGias");

                    b.Navigation("DonDatSans");

                    b.Navigation("HinhAnhSans");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.Voucher", b =>
                {
                    b.Navigation("DonDatSans");
                });
#pragma warning restore 612, 618
        }
    }
}
